### ISSUE TITLE
Fetching Data

### ISSUE THREAD

**Issue by steeeved** [FMirzaei93/quizzical-app#1]
Hi there Rose. 
I have gone through your code and it is really nice. I however did not get my head around how you were fetching the questions data.
Could kindly you help me figure out how you did it.
p.s I am a frontend newbie, let us connect
Here is my email address  -: muchendumaina66@gmail.com
Looking forward to hearing from you!

**Comment by FMirzaei93** [comment]
Hi Stephen, thanks for checking out my code.

```
function fetchData() {
   1. fetch("https://opentdb.com/api.php?amount=5")
   2. then((response) => response.json())
   3. then((data) => createObjArray(data.results))
   4. .then((objsArray) => setQuestionsArray(objsArray))
   5. .finally(() => {
   6.     setIsFetched(true);
      });
  }
```
This is the simplified version of the fetching function. The rest was for handling network errors that I erased to be easier to explain the code.
In order for you to understand the code better, I specified each line with a number(so you just remove them), and follow the explanation of each number below:

**1.** here I’m sending a request to the server. You can easily see the result of any request using the [Postman](https://www.postman.com) application. The result of this request is shown below:

`{
    "response_code": 0,
    "results": [
        {
            "category": "Entertainment: Video Games",
            "type": "multiple",
            "difficulty": "medium",
            "question": "In Need For Speed: Most Wanted (2005), how many people are there to defeat on the blacklist?",
            "correct_answer": "15",
            "incorrect_answers": [
                "5",
                "10",
                "20"
            ]
        },
        {
            "category": "Entertainment: Video Games",
            "type": "multiple",
            "difficulty": "easy",
            "question": "Valve Corporation is an American video game developer located in which city?",
            "correct_answer": "Bellevue, Washington",
            "incorrect_answers": [
                "Austin, Texas",
                "Seattle, Washington",
                "San Francisco, California"
            ]
        },...
])
`

_Instead of using Postman you can also see the result easily by `console.log()` in the line number2 (that I’ll explain all below) by writing: `then((response) =>console.log(response))`_

**2.** here I have caught the data so far(“**response**” is the whole data we fetched from the server), but it’s in the String format, I need to convert it to the Json format (Json object), so I can parse and get the data easily, that's why here we have `response.json()`

**3.** here “**data**” is the result of the upper line, in fact, it’s the same as “**response.json()**”. So now we have our data in “Json format”. 
As you can see in the fetched data above, this Json object contains: “**response_code**” and “**results**”(which “results” is an array of question objects), we want to get only the “results” array to parse it and to have every question respectively. That’s why here we have “**data.result**”. 
Now using the “**createObjArray**” function, I tried to add even more properties to each question object that I’m receiving.
_(In this function I’m using the map function to make some changes in the raw array(**data.results**) that I received from the server)_  

**4.** here “**objsArray**” is the same as “**createObjArray(data.results)**” in the upper line, that I’d like to save this value(an array of questions plus my new-added properties) in a ReactState (**questionArray**) (that I’ve defined in App.js above the whole codes) by using **setQuestionArray**.

**5.** In this section, I’m using another ReactState for my personal purpose.
_(It says when the process of fetching the data is all the way done, set isFetched state to true)._

That’s all about this part, not sure if you were looking for this part explanation or not! Please let me know if you run into any other problems or questions.

**Comment by steeeved** [comment]
Wow, this is really inciteful. Thank you!
